# 这里是工作流名称
name: Docker Image CI

# 这里是触发条件
on:
  push:
    branches: [ release ]

# 这里是任务
jobs:
  # 任务名称, 构建任务
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 这里是运行步骤
    steps:
    # 这里是动作
    - name: Checkout action
      uses: actions/checkout@v2
    # 这里是构建镜像
    - name: Build the Docker image
      working-directory: ./soulmangaadmin
      run: |
        docker build . --file Dockerfile --tag soulmangaadmin:latest
        mkdir docker
        docker save soulmangaadmin | gzip > docker/my-image-name.tar.gz
    # 这里是部署
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.ACCESS_TOKEN }}
      with:
        source: "soulmangaadmin"
        target: "Code"
    
  # 部署任务
  display:
    name: Display wait build finished
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.ACCESS_TOKEN }}
        port: ${{ secrets.PORT }}
        script: |
          cd Code/soulmangaadmin
          ls
